name: Check for new release and update the input file with latest information.

on:
  push:
    branches:
      - main
#on:
 # schedule:
  #  - cron: '24 10 31 5 *' 

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
          
      - name: Show input YAML file
        run: cat input.yaml
      
      - name: Run update script
        run: python testing.py

      - name: Show file changes
        run: git status
    
      - name: Show updated input YAML file
        run: cat input.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'Bhav21v'
          git config --global user.email 'bhvaid21@gmail.com'
          git add input.yaml
          git commit -m 'Update input.yaml with new release information'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Show file changes
        run: git status
