name: Check for new release and update the input file with latest information.

on:
  workflow_dispatch: 
  schedule:
    - cron: '22 18 10 6 *' 

jobs:
  update-yaml:
    runs-on: ubuntu-latest

 # Give the default GITHUB_TOKEN write permission to commit and push the added or changed files to the repository.
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
         ref: ${{ github.head_ref }}
         
      - uses: actions/checkout@v4
        with:
         token: ${{ secrets.PAT }}  
         
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
          
      - name: Show input YAML file
        run: cat input.yaml
      
      - name: Run update script
        run: python Version_Check.py

      - name: Show file changes
        run: git status
    
      - name: Show updated input YAML file
        run: cat input.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'Bhav21v'
          git config --global user.email 'bhvaid21@gmail.com'
          git add input.yaml
          git commit -m 'Update input.yaml with new release information'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.PAT }}
