name: Check for new release and update the input file with latest information.

#on:
#  push:
 #   branches:
  #    - main
on:
  workflow_dispatch: 
  schedule:
    - cron: '10 13 31 5 *' 

jobs:
  update-yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests
          
      - name: Show input YAML file
        run: cat input.yaml
      
      - name: Run update script
        run: python Version_Check.py

      - name: Show file changes
        run: git status
    
      - name: Show updated input YAML file
        run: cat input.yaml

      - name: Commit changes
        run: |
          git config --global user.name 'kempas01'
          git config --global user.email 'srinath.kempanna@pfizer.com'
          git add -A
          git commit -m 'Update input.yaml with new release information'
       

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.PAT }}

      - name: Show file changes
        run: git status
